# Clock and Reset
set_property IOSTANDARD LVCMOS33 [get_ports Ethernet125Mhz]
set_property PACKAGE_PIN L16 [get_ports Ethernet125Mhz]

set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property PACKAGE_PIN Y16 [get_ports reset_rtl]

# NES Controller pins
set_property IOSTANDARD LVCMOS33 [get_ports data]
set_property PACKAGE_PIN V13 [get_ports data]

set_property IOSTANDARD LVCMOS33 [get_ports latch]
set_property PACKAGE_PIN U17 [get_ports latch]

set_property IOSTANDARD LVCMOS33 [get_ports pulse]
set_property PACKAGE_PIN T17 [get_ports pulse]

# VGA
set_property IOSTANDARD LVCMOS33 [get_ports {blue[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN G19 [get_ports {blue[4]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN K19 [get_ports {blue[2]}]
set_property PACKAGE_PIN M20 [get_ports {blue[1]}]
set_property PACKAGE_PIN P20 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R19 [get_ports v_sync]
set_property PACKAGE_PIN F20 [get_ports {green[5]}]
set_property PACKAGE_PIN H20 [get_ports {green[4]}]
set_property PACKAGE_PIN J19 [get_ports {green[3]}]
set_property PACKAGE_PIN L19 [get_ports {green[2]}]
set_property PACKAGE_PIN N20 [get_ports {green[1]}]
set_property PACKAGE_PIN H18 [get_ports {green[0]}]
set_property PACKAGE_PIN F19 [get_ports {red[4]}]
set_property PACKAGE_PIN G20 [get_ports {red[3]}]
set_property PACKAGE_PIN J20 [get_ports {red[2]}]
set_property PACKAGE_PIN L20 [get_ports {red[1]}]
set_property PACKAGE_PIN M19 [get_ports {red[0]}]

# GPIO
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches_tri_i[0]}]
set_property PACKAGE_PIN V16 [get_ports {btns_tri_i[2]}]
set_property PACKAGE_PIN P16 [get_ports {btns_tri_i[1]}]
set_property PACKAGE_PIN R18 [get_ports {btns_tri_i[0]}]
set_property PACKAGE_PIN D18 [get_ports {leds_tri_o[3]}]
set_property PACKAGE_PIN G14 [get_ports {leds_tri_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {leds_tri_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN T16 [get_ports {switches_tri_i[3]}]
set_property PACKAGE_PIN W13 [get_ports {switches_tri_i[2]}]
set_property PACKAGE_PIN P15 [get_ports {switches_tri_i[1]}]
set_property PACKAGE_PIN G15 [get_ports {switches_tri_i[0]}]

# I2C
set_property PACKAGE_PIN N18 [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN N17 [get_ports iic_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]
