webtalk_init -webtalk_dir D:\\XilinxProjects\\SeniorProject\\SeniorProject.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 18 00:35:51 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210772452_1777500221_210581215_921" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d68sjrt1mev4jbfmcutqpip96j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3293 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1447811193662" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1447811193662"
webtalk_add_data -client sdk -key uid -value "1447811218402" -context "sdk\\\\bsp/1447811218402"
webtalk_add_data -client sdk -key hwid -value "1447811193662" -context "sdk\\\\bsp/1447811218402"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1447811218402"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1447811218402"
webtalk_add_data -client sdk -key uid -value "1447811224140" -context "sdk\\\\application/1447811224140"
webtalk_add_data -client sdk -key hwid -value "1447811193662" -context "sdk\\\\application/1447811224140"
webtalk_add_data -client sdk -key bspid -value "1447811218402" -context "sdk\\\\application/1447811224140"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1447811224140"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1447811224140"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1447811224140"
webtalk_transmit -clientid 554075086 -regid "210772452_1777500221_210581215_921" -xml D:\\XilinxProjects\\SeniorProject\\SeniorProject.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\XilinxProjects\\SeniorProject\\SeniorProject.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\XilinxProjects\\SeniorProject\\SeniorProject.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
